/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void appRunsWithoutErrors() {
        // simple test to just run main method without exception
        try {
            App.main(new String[0]);
        } catch (Exception e) {
            fail("App.main threw an exception: " + e.getMessage());
        }
    }
}
